### ISSUE TITLE
Local file inclusion vulnerability

### ISSUE THREAD

**Issue by themcaffee** [stuntnmore/DSMA#2]
In `dedicated_server_management/dedicated_server_management.php` on line 49:

```
include ($_GET[page].".php");
```

there is a local file inclusion vulnerability. `page` is not sanitized and by using a null byte character can be used to include any file on the server. [More information](http://resources.infosecinstitute.com/file-inclusion-attacks/)

**Comment by stuntnmore** [comment]
This has been resolved, thank you
